export default {
  // Common
  loading: 'چاوەڕوان بە...',
  error: 'هەڵەیەک ڕوویدا',
  save: 'پاشەکەوتکردن',
  cancel: 'پاشگەزبوونەوە',
  delete: 'سڕینەوە',
  edit: 'دەستکاری',
  add: 'زیادکردن',
  close: 'داخستن',
  confirm: 'پشتڕاستکردنەوە',
  back: 'گەڕانەوە',
  search: 'گەڕان',
  filter: 'پاڵاوتن',
  sort: 'ڕیزکردن',
  all: 'هەموو',
  yes: 'بەڵێ',
  no: 'نەخێر',
  submit: 'ناردن',
  success: 'سەرکەوتن',
  required: 'پێویستە',
  optional: 'ئارەزووی',
  view: 'بینین',
  approve: 'پەسەندکردن',
  reject: 'ڕەتکردنەوە',
  active: 'چالاک',
  inactive: 'ناچالاک',
  seeAll: 'هەموویان ببینە',
  never: 'هەرگیز',
  expired: 'بەسەرچووە',
  notProvided: 'نەدراوە',
  tryAgain: 'هەڵەیەک ڕوویدا. تکایە دووبارە هەوڵبدەرەوە.',
  orderId: 'ژمارەی داواکاری',

  // Nav tabs
  shop: 'بازاڕ',
  cart: 'سەبەتە',
  canopy: 'چاودێری پێست',
  account: 'ئەکاونت',

  // Header
  viewStore: 'بینینی فرۆشگا',
  store: 'فرۆشگا',

  // Home / Shop
  heroDefault: {
    badge: 'ئارایشی پریمیەم',
    title: 'جوانی خۆت بەرز بکەرەوە',
    subtitle: 'ئارایشی پریمیەم کە زیاتر لە ١٠،٠٠٠ کەسی خۆشەویستی جوانی دووری نیازی',
  },
  sortBy: 'ڕیزکردن بەپێی',
  sortFeatured: 'بەرز',
  sortPriceAsc: 'نرخ: لە کەمەوە بۆ زۆر',
  sortPriceDesc: 'نرخ: لە زۆرەوە بۆ کەم',
  sortRating: 'نمرەی بەرز',
  products: 'بەرهەم',
  product: 'بەرهەم',
  noGearFound: 'هیچ بەرهەمێک نەدوزرایەوە',
  tryDifferentSearch: 'گەڕانێکی تر هەوڵبدەرەوە',
  searchPlaceholder: 'گەڕان بۆ ئارایش...',

  // Cart
  yourCart: 'سەبەتەکەت',
  items: 'بەند',
  item: 'بەند',
  orderSummary: 'پوختەی داواکاری',
  subtotal: 'کۆی بەشێک',
  shipping: 'گەیاندن',
  free: 'بەخۆڕایی',
  total: 'کۆی گشتی',
  proceedToCheckout: 'بڕۆ بۆ پارەدان',
  cartEmpty: 'سەبەتەکەت بەتاڵە',
  cartEmptySubtitle: 'بەرهەمی جوانی بدۆزەرەوە و دەست بکە بە کڕین',
  browseGear: 'بینینی بەرهەمەکان',
  addMoreForFreeShipping: 'زیادکردنی ${{amount}} بۆ گەیاندنی بەخۆڕایی',

  // Account
  welcomeBack: 'بەخێربێی دووبارە',
  createAccount: 'دروستکردنی ئەکاونت',
  signIn: 'چوونەژوورەوە',
  login: 'چوونەژوورەوە',
  register: 'تۆمارکردن',
  signInSubtitle: 'بچۆ ژوورەوە بۆ ئەکاونتی Lazurde',
  registerSubtitle: 'بکەوە ناو کۆمەڵگەی ئەمەی ئارایش',
  email: 'ئیمەیڵ',
  password: 'وشەی نهێنی',
  confirmPassword: 'دووپاتکردنەوەی وشەی نهێنی',
  firstName: 'ناوی یەکەم',
  lastName: 'ناوی دووەم',
  emailPlaceholder: 'ئیمەیڵەکەت@مەیل.کۆم',
  passwordPlaceholder: 'کەمترین ٦ پیت',
  invalidEmail: 'تکایە ئیمەیڵێکی دروست بنووسە',
  passwordRequired: 'تکایە وشەی نهێنیەکەت بنووسە',
  firstNameRequired: 'ناوی یەکەم پێویستە',
  lastNameRequired: 'ناوی دووەم پێویستە',
  validEmailRequired: 'ئیمەیڵێکی دروست پێویستە',
  passwordMinLength: 'وشەی نهێنی دەبێت کەمترین ٦ پیت بێت',
  passwordsNoMatch: 'وشەکانی نهێنی یەکسان نین',
  invalidCredentials: 'زانیارییەکان هەڵەن. دووبارە هەوڵبدەرەوە.',
  jumps: 'ڕووتین',
  orders: 'داواکاری',
  level: 'ئاست',
  orderHistory: 'مێژووی داواکاری',
  loadingOrders: 'بارکردنی داواکاریەکان...',
  noOrdersYet: 'هیچ داواکاریەک نییە',
  purchasesWillAppear: 'کڕینەکانت لێرە دەرکەوێت',

  // Product Detail
  selectShade: 'ڕەنگێک هەڵبژێرە',
  pleaseSelectShade: 'تکایە پێش زیادکردن بۆ سەبەتە ڕەنگێک هەڵبژێرە',
  tryOn: 'تاقیکردنەوە',
  addToCart: 'زیادکردن بۆ سەبەتە',
  addedToCart: 'زیادکرا بۆ سەبەتە!',
  inCart: 'لە سەبەتەدا',
  inStock: 'بەردەستە',
  onlyLeft: 'تەنها {{n}} ماوەتەوە',
  outOfStock: 'تەواوبووە',
  freeShipping: 'گەیاندنی بەخۆڕایی بۆ زیاتر لە $٥٠',
  securePayment: 'پارەدانی پارێزراو',
  specifications: 'تایبەتمەندی',
  category: 'جۆر',
  sku: 'کۆدی بەرهەم',
  description: 'باسکردن',
  quantity: 'ژمارە',
  proTested: 'تاقیکراوەی پیشەیی',
  topRated: 'نمرەی بەرز',

  // Checkout
  checkout: 'پارەدان',
  shippingInfo: 'زانیاری کڕیار',
  paymentMethod: 'شێوازی پارەدان',
  creditCard: 'کارتی کرێدیت',
  paypal: 'پەیپاڵ',
  applePay: 'ئەپڵ پەی',
  phone: 'تەلەفۆن',
  address: 'ناونیشان',
  city: 'شار',
  state: 'ووڵات',
  zip: 'کۆدی بریتانیا',
  country: 'وڵات',
  placeOrder: 'داواکاری بنێرە',
  orderPlaced: 'داواکاری نێردرا!',
  orderPlacedSubtitle: 'سوپاس بۆ داواکاریەکەت. بەم زووانە ئامادەت دەکەین.',
  continueShopping: 'بەردەوامبوون لە کڕین',
  fieldRequired: 'ئەم خانەیە پێویستە',
  validPhoneRequired: 'تکایە ژمارەی تەلەفۆنێکی دروست بنووسە',

  // Wishlist
  myWishlist: 'دڵخوازەکانم',
  addedToWishlist: 'زیادکرا بۆ دڵخوازەکان',
  removedFromWishlist: 'لە دڵخوازەکان سڕایەوە',
  wishlistEmpty: 'دڵخوازەکانت بەتاڵن',
  wishlistEmptyDesc: 'ئایکۆنی دڵ لەسەر هەر بەرهەمێک بکە بۆ پاشەکەوتکردنی.',
  signInToSave: 'بچۆ ژوورەوە بۆ پاشەکەوتکردنی دڵخوازەکان',
  signInToSaveDesc: 'ئەکاونتێک دروستبکە بۆ پاشەکەوتکردنی بەرهەمەکان.',
  clearWishlist: 'پاکردنەوەی دڵخوازەکان',
  clearWishlistConfirm: 'هەموو بەندەکان لە دڵخوازەکانت بسڕیتەوە؟',
  clearAll: 'هەموویان بسڕەوە',
  browseProducts: 'بینینی بەرهەمەکان',

  // Nav labels
  navHome: 'سەرەکی',
  navShop: 'بازاڕ',
  navSaved: 'پاشەکەوتکراو',
  navProducts: 'بەرهەمەکان',
  navAllProducts: 'هەموو بەرهەمەکان',
  navCart: 'سەبەتە',
  navAdminPanel: 'پانێلی بەڕێوەبردن',
  navCanopyFinder: 'فیلتەری جۆر',
  navAccount: 'ئەکاونت',
  navAbout: 'دەربارەی',

  // Search
  searchGear: 'گەڕان بۆ ئارایش...',

  // Language names
  english: 'ئینگلیزی',
  arabic: 'عەرەبی',
  spanish: 'ئیسپانی',
  german: 'ئەڵمانی',
  russian: 'ڕووسی',
  kurdish: 'کوردی',

  // Multilingual product editor
  nameKurdish: 'ناو (کوردی)',
  descKurdish: 'وەسف (کوردی)',
};
