export default {
  // Common
  loading: 'Loading...',
  error: 'Something went wrong',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  add: 'Add',
  close: 'Close',
  confirm: 'Confirm',
  back: 'Back',
  search: 'Search',
  filter: 'Filter',
  sort: 'Sort',
  all: 'All',
  yes: 'Yes',
  no: 'No',
  submit: 'Submit',
  success: 'Success',
  required: 'Required',
  optional: 'Optional',
  view: 'View',
  approve: 'Approve',
  reject: 'Reject',
  active: 'Active',
  inactive: 'Inactive',
  seeAll: 'See all',
  never: 'Never',
  expired: 'Expired',
  notProvided: 'Not provided',
  tryAgain: 'Something went wrong. Please try again.',
  orderId: 'Order ID',

  // Nav tabs
  shop: 'Shop',
  cart: 'Cart',
  canopy: 'Skincare',
  account: 'Account',

  // Header
  viewStore: 'View Store',
  store: 'Store',

  // Home / Shop
  heroDefault: {
    badge: 'PREMIUM MAKEUP',
    title: 'Elevate Your\nBeauty',
    subtitle: 'Premium makeup loved by 10,000+ beauty enthusiasts worldwide',
  },
  sortBy: 'Sort By',
  sortFeatured: 'Featured',
  sortPriceAsc: 'Price: Low to High',
  sortPriceDesc: 'Price: High to Low',
  sortRating: 'Highest Rated',
  products: 'products',
  product: 'product',
  noGearFound: 'No products found',
  tryDifferentSearch: 'Try a different search or category',
  searchPlaceholder: 'Search beauty...',

  // Cart
  yourCart: 'Your Cart',
  items: 'items',
  item: 'item',
  orderSummary: 'Order Summary',
  subtotal: 'Subtotal',
  shipping: 'Shipping',
  free: 'FREE',
  total: 'Total',
  proceedToCheckout: 'Proceed to Checkout',
  cartEmpty: 'Your cart is empty',
  cartEmptySubtitle: 'Discover premium beauty products and start shopping',
  browseGear: 'Browse Products',
  addMoreForFreeShipping: 'Add ${{amount}} more for free shipping',

  // Account
  welcomeBack: 'Welcome Back',
  createAccount: 'Create Account',
  signIn: 'Sign In',
  login: 'Login',
  register: 'Register',
  signInSubtitle: 'Sign in to your Lazurde Makeup account',
  registerSubtitle: 'Join our community of makeup enthusiasts',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  firstName: 'First Name',
  lastName: 'Last Name',
  emailPlaceholder: 'your@email.com',
  passwordPlaceholder: 'Min 6 characters',
  invalidEmail: 'Please enter a valid email',
  passwordRequired: 'Please enter your password',
  firstNameRequired: 'First name is required',
  lastNameRequired: 'Last name is required',
  validEmailRequired: 'Valid email required',
  passwordMinLength: 'Password must be at least 6 characters',
  passwordsNoMatch: 'Passwords do not match',
  invalidCredentials: 'Invalid credentials. Please try again.',
  jumps: 'Routine',
  orders: 'Orders',
  level: 'Level',
  orderHistory: 'Order History',
  loadingOrders: 'Loading orders...',
  noOrdersYet: 'No orders yet',
  purchasesWillAppear: 'Your purchases will appear here',

  // Skincare Section
  canopyAdvisor: 'Skincare',
  canopySubtitle: 'Our premium skincare collection is coming soon. Stay tuned for personalized recommendations.',
  yourWeight: 'Skin Type',
  weightPlaceholder: 'e.g. Oily',
  weightPlaceholderKg: 'e.g. Dry',
  experienceLevel: 'Experience Level',
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  advanced: 'Advanced',
  expert: 'Expert',
  beginnerDesc: 'New to skincare',
  intermediateDesc: 'Basic routine',
  advancedDesc: 'Multi-step routine',
  expertDesc: 'Professional level',
  getRecommendation: 'Coming Soon',
  calculating: 'Calculating...',
  recommendation: 'Recommendation',
  wingLoading: 'Coverage',
  suggestedSize: 'Suggested Shade',
  safetyNote: 'Beauty Tip',
  matchingProducts: 'Recommended Products',
  matchingProductsSubtitle: 'Curated skincare products from our catalog',
  safe: 'Gentle',
  caution: 'Moderate',
  risky: 'Intense',
  low: 'Light',
  reset: 'Reset',
  yourProfile: 'Your Profile',
  enterWeightAndJumps: 'Tell us about your skin type and beauty routine',
  totalJumps: 'Routine Steps',
  totalJumpsPlaceholder: 'e.g. 5',
  weightHint: 'Consider your skin sensitivity and any specific concerns',
  canopyDisclaimer: 'Based on dermatological guidelines and beauty industry best practices. Not medical advice.',
  canopySafetyFinal: 'For specific skin concerns, consult a dermatologist. This tool provides guidance only.',
  weightRangeLbs: 'Please select a valid skin type.',
  weightRangeKg: 'Please select a valid skin type.',
  invalidJumps: 'Please enter a valid routine step count.',
  yourRecommendation: 'Your Recommendation',
  recommendedSizeRange: 'Recommended Product Range',
  suggestedSizes: 'Suggested Products',
  howCalculated: 'How This Was Calculated',
  wingLoadingFormula: 'skin type + concerns = ideal routine',
  safeRangeFor: 'Best Products for',
  wingLoadingBySuggestedSize: 'Product Match by Skin Type',
  highWingLoadingWarning: 'This product may be too intense for your skin type.',
  lowWingLoadingNote: 'Very gentle formula. Great for sensitive skin but may need layering for full effect.',
  riskyConfigWarning: 'This combination may not suit your skin type. Consider a gentler alternative.',
  beginnerHighPerfWarning: 'Professional-grade products require experience. Start with our beginner-friendly range.',
  sqft: 'ml',
  lbSqFt: 'coverage',

  // Product Detail
  selectShade: 'Select a shade',
  pleaseSelectShade: 'Please select a shade before adding to cart',
  tryOn: 'Try On',
  addToCart: 'Add to Cart',
  addedToCart: 'Added to Cart!',
  inCart: 'in cart',
  inStock: 'In Stock',
  onlyLeft: 'Only {{n}} left',
  outOfStock: 'Out of Stock',
  freeShipping: 'Free shipping over $50',
  securePayment: 'Secure payment',
  specifications: 'Specifications',
  category: 'Category',
  sku: 'SKU',
  description: 'Description',
  quantity: 'Quantity',
  proTested: 'Pro Tested',
  topRated: 'Top Rated',

  // Checkout
  checkout: 'Checkout',
  shippingInfo: 'Customer Info',
  paymentMethod: 'Payment Method',
  creditCard: 'Credit Card',
  paypal: 'PayPal',
  applePay: 'Apple Pay',
  phone: 'Phone',
  address: 'Street Address',
  city: 'City',
  state: 'State',
  zip: 'ZIP Code',
  country: 'Country',
  placeOrder: 'Place Order',
  orderPlaced: 'Order Placed!',
  orderPlacedSubtitle: "Thank you for your order. We'll get it ready for you soon.",
  continueShopping: 'Continue Shopping',
  fieldRequired: 'This field is required',
  validPhoneRequired: 'Please enter a valid phone number',

  // Admin nav
  admin: 'Admin',
  dashboard: 'Dashboard',
  products: 'Products',
  categories: 'Categories',
  ordersAdmin: 'Orders',
  customers: 'Customers',
  employees: 'Employees',
  reviews: 'Reviews',
  coupons: 'Coupons',
  homeSections: 'Home Sections',
  content: 'Content',
  pageBuilder: 'Page Builder',
  layoutSpacing: 'Layout & Spacing',
  uiSizes: 'UI Size Manager',
  settings: 'Settings',
  signOut: 'Sign Out',
  language: 'Language',
  selectLanguage: 'Select Language',

  // Admin Dashboard
  totalRevenue: 'Total Revenue',
  totalOrders: 'Total Orders',
  totalProducts: 'Total Products',
  totalCustomers: 'Total Customers',
  recentOrders: 'Recent Orders',
  quickActions: 'Quick Actions',
  viewOrders: 'View Orders',
  editContent: 'Edit Content',

  // Admin Products
  addProduct: 'Add Product',
  editProduct: 'Edit Product',
  productName: 'Product Name',
  price: 'Price',
  stock: 'Stock',
  imageUrl: 'Image URL',
  badge: 'Badge',
  rating: 'Rating',
  featured: 'Featured',
  lowStock: 'Low Stock',
  noProductsFound: 'No products yet',
  addFirstProduct: 'Add your first product to get started',
  searchProducts: 'Search products...',
  productNamePlaceholder: 'e.g. Velvet Matte Lipstick',
  descriptionPlaceholder: 'Enter product description...',
  imagePreviewHint: 'Enter an image URL above to preview',
  colProduct: 'Product',
  colPrice: 'Price',
  colStock: 'Stock',
  colFeatured: 'Featured',
  colActions: 'Actions',
  tryClearingFilters: 'Try clearing your filters',
  markFeatured: 'Mark as Featured',

  // Admin Orders
  updateStatus: 'Update Status',
  noOrdersFound: 'No orders yet',
  ordersPending: 'Orders will appear here when customers place them',
  searchOrders: 'Search orders...',
  colCustomer: 'Customer',
  colTotal: 'Total',
  colStatus: 'Status',
  colDate: 'Date',
  orderDetails: 'Order Details',
  orderItems: 'Order Items',
  noItems: 'No items',
  shippingAddress: 'Shipping Address',
  contactInfo: 'Contact Info',
  paymentInfo: 'Payment',
  ordersCount: 'orders',

  // Admin Customers
  noCustomersYet: 'No customers yet',
  customersAppearAfterOrders: 'Customers appear after orders are placed',
  searchCustomers: 'Search customers...',
  customersCount: 'customers',
  colSpent: 'Spent',
  totalSpent: 'Total Spent',
  customerDetails: 'Customer Details',

  // Admin Employees
  addEmployee: 'Add Employee',
  editEmployee: 'Edit Employee',
  employee: 'Employee',
  noEmployeesYet: 'No employees yet',
  addFirstEmployee: 'Add your first team member',
  searchEmployees: 'Search employees...',
  employeesCount: 'employees',
  employeeCount: 'employee',
  role: 'Role',
  department: 'Department',
  hireDate: 'Hire Date',
  salaryUsd: 'Salary (USD)',
  emergencyContact: 'Emergency Contact',
  emergencyPhone: 'Emergency Phone',
  notes: 'Notes',
  activeEmployee: 'Active Employee',
  colRole: 'Role',
  colDept: 'Dept',
  personalInfo: 'Personal Information',
  employmentInfo: 'Employment Info',
  fullName: 'Full Name',
  permissions: 'Permissions',
  cannotBeUndone: 'This action cannot be undone.',
  deleted: 'Deleted',

  // Admin Reviews
  searchReviews: 'Search reviews...',
  reviewsCount: 'reviews',
  reviewCount: 'review',
  pending: 'Pending',
  approved: 'Approved',
  rejected: 'Rejected',
  noReviewsYet: 'No reviews yet',
  reviewsAppearWhenSubmitted: 'Reviews appear here when customers submit them',
  reviewDetails: 'Review Details',
  submitted: 'Submitted',
  colReviewer: 'Reviewer',
  colRating: 'Rating',
  colProduct: 'Product',

  // Admin Coupons
  addCoupon: 'Add Coupon',
  editCoupon: 'Edit Coupon',
  noCouponsYet: 'No coupons yet',
  createFirstCoupon: 'Create your first discount coupon',
  searchCoupons: 'Search coupons...',
  couponsCount: 'coupons',
  couponCount: 'coupon',
  discountType: 'Discount Type',
  percentage: 'Percentage',
  fixedAmount: 'Fixed Amount',
  discountValue: 'Discount Value',
  minOrder: 'Min. Order ($)',
  expiryDate: 'Expiry Date',
  usageLimit: 'Usage Limit',
  timesUsed: 'Times Used',
  couponCode: 'Coupon Code',
  couponCodePlaceholder: 'e.g. SAVE20',
  noMinOrder: 'Any',
  colCode: 'Code',
  colDiscount: 'Discount',
  colExpiry: 'Expiry',
  colUsage: 'Usage',

  // Admin Content
  heroContent: 'Hero Banner',
  featuredContent: 'Featured',
  canopyContent: 'Skincare',
  testimonialsContent: 'Testimonials',
  footerContent: 'Footer',
  contentEditHint: 'Edit your homepage content. Changes are saved to the database and reflected on the storefront.',
  saveChanges: 'Save Changes',
  saved: 'Saved!',
  noImageSet: 'No image URL set',
  textContent: 'Text Content',
  badgeText: 'Badge Text',
  heroTitle: 'Hero Title',
  heroSubtitle: 'Hero Subtitle',
  buttons: 'Buttons',
  ctaPrimary: 'CTA Primary',
  ctaSecondary: 'CTA Secondary',
  sectionTitle: 'Section Title',
  sectionSubtitle: 'Section Subtitle',
  featuredHint: 'To mark products as featured, go to the Products module and toggle "Mark as Featured" when editing a product.',
  testimonialsHint: 'Testimonials are pulled from approved reviews. Manage individual reviews in the Reviews section.',
  footerTagline: 'Footer Tagline',
  footerEmail: 'Footer Email',
  footerPhone: 'Footer Phone',
  copyrightText: 'Copyright Text',

  // Admin Settings
  storeSettings: 'Store Settings',
  languageSettings: 'Language Settings',
  appLanguage: 'App Language',
  changeLanguage: 'Change Language',
  storeIdentity: 'Store Identity',
  storeName: 'Store Name',
  storeTagline: 'Store Tagline',
  logoUrl: 'Logo URL',
  contactInformation: 'Contact Information',
  socialLinks: 'Social Links',
  commerceSettings: 'Commerce Settings',
  localization: 'Localization',
  adminInfo: 'Admin Info',
  configureStore: 'Configure your store\'s identity, contact info, social links, and commerce settings.',
  freeShippingThreshold: 'Free Shipping Threshold ($)',
  taxRate: 'Tax Rate (%)',
  currencyCode: 'Currency Code',
  timezone: 'Timezone',
  defaultLanguage: 'Default Language',
  instagramUrl: 'Instagram URL',
  facebookUrl: 'Facebook URL',
  twitterUrl: 'Twitter URL',
  youtubeUrl: 'YouTube URL',
  supportEmail: 'Support Email',
  supportPhone: 'Support Phone',

  // Language names
  english: 'English',
  arabic: 'Arabic',
  spanish: 'Spanish',
  german: 'German',
  russian: 'Russian',

  // Multilingual product editor
  translations: 'Translations',
  translationTab: 'Translation',
  missingTranslation: 'Missing translation',
  saveEnglish: 'Save English',
  saveArabic: 'Save Arabic',
  saveSpanish: 'Save Spanish',
  saveGerman: 'Save German',
  saveRussian: 'Save Russian',
  translationSaved: 'Translation saved',
  translationsMissing: 'translations missing',
  noTranslation: 'No translation',
  productNameTranslation: 'Product Name (translated)',
  descriptionTranslation: 'Description (translated)',
  translationNote: 'Fallback to English if empty',
  saveTranslation: 'Save Translation',
  coreFields: 'Core Fields',

  // Admin Layout & Spacing editor
  layoutSpacingSubtitle: 'Control spacing, typography and layout per section',
  loadingLayout: 'Loading layout settings…',
  errorLoadingLayout: 'Error loading layout',
  retry: 'Retry',
  previewOn: 'Preview On',
  previewOff: 'Preview Off',
  resetAll: 'Reset All',
  saveAll: 'Save All',
  saving: 'Saving…',
  savedBang: 'Saved!',
  sections: 'Sections',
  blocks: 'blocks',
  dragToReorder: 'Drag grip to reorder',
  saveSection: 'Save Section',
  resetSection: 'Reset',
  spacing: 'Spacing',
  typography: 'Typography',
  layout: 'Layout',
  livePreview: 'Live Preview',
  mobile: 'Mobile',
  tablet: 'Tablet',
  desktop: 'Desktop',
  breakpoint: 'Breakpoint',
  components: 'Components',

  // Layout section names
  sectionHeader: 'Header',
  sectionHero: 'Hero Banner',
  sectionFeatured: 'Best Sellers',
  sectionCanopy: 'Skincare',
  sectionTestimonials: 'Testimonials',
  sectionBanner: 'Promo Banner',
  sectionFooter: 'Footer',
  sectionProducts: 'Product Grid',

  // Layout section descriptions
  descHeader: 'App bar at the top',
  descHero: 'Full-width banner',
  descFeatured: 'Featured products grid',
  descCanopy: 'Skincare section block',
  descTestimonials: 'Reviews carousel',
  descBanner: 'Promotional strip',
  descFooter: 'Footer block',
  descProducts: 'Product listing grid',

  // UI Size Manager
  uiSizesSubtitle: 'Control sizes, spacing and measurements across the storefront',
  loadingSizes: 'Loading size settings…',
  errorLoadingSizes: 'Error loading settings',
  saveCategory: 'Save',

  // Page Builder
  savingLayout: 'Saving layout…',
  layoutSaved: 'Layout saved successfully!',
  saveFailed: 'Save failed — try again',
  noVisibleBlocks: 'No visible blocks',
  addBlock: 'Add a Block',
  dropHere: 'Drop here',
  loadingPageLayout: 'Loading page layout…',
  errorLoadingPageLayout: 'Error loading layout',
  noLayoutFound: 'No layout data found',
  noLayoutDesc: 'The page layout could not be loaded. Create a default layout to get started.',
  createDefaultLayout: 'Create Default Layout',

  // Block type labels & descriptions
  blockLabelHeader: 'Header',
  blockLabelHero: 'Hero Banner',
  blockLabelFeatured: 'Featured',
  blockLabelCanopy: 'Skincare',
  blockLabelTestimonials: 'Testimonials',
  blockLabelBanner: 'Promo Banner',
  blockLabelFooter: 'Footer',
  blockDescHeader: 'App bar with logo & navigation',
  blockDescHero: 'Full-width image with title & CTA',
  blockDescFeatured: 'Grid of featured products',
  blockDescCanopy: 'Skincare section placeholder',
  blockDescTestimonials: 'Customer reviews & ratings',
  blockDescBanner: 'Promotional strip with link',
  blockDescFooter: 'Footer with links & copyright',

  // CMS Content editor
  contentManager: 'Content Manager',
  siteEditor: 'Site Editor',
  cmsContentTitle: 'CMS Content',
  loadingContent: 'Loading content...',
  hidePreview: 'Hide Preview',
  showPreview: 'Show Preview',
  languageLabel: 'Language:',
  logoBranding: 'Logo & Branding',
  logoImage: 'Logo Image',
  logoImageHint: 'Upload your logo or paste a URL. Leave blank to show text logo.',
  appIdentity: 'App Identity',
  appName: 'App Name',
  appTagline: 'App Tagline',
  appTaglineHint: 'Shown after app name in header and drawer',
  showHeaderIcons: 'Show Header Icons (Cart & Account)',
  heroBanner: 'Hero Banner',
  backgroundImage: 'Background Image',
  backgroundImageHint: 'Upload from computer or paste a URL. Appears full-width behind hero text.',
  overlayColor: 'Overlay Color',
  overlayColorHint: 'CSS rgba color layered over image for text legibility',
  primaryButton: 'Primary Button',
  secondaryButton: 'Secondary Button',
  featuredProductsSection: 'Featured Products Section',
  showFeaturedSection: 'Show Featured Section',
  canopyFinderSection: 'Skincare Section',
  canopyDescription: 'Description',
  ctaButtonText: 'CTA Button Text',
  showCanopySection: 'Show Skincare Section',
  testimonialsSection: 'Testimonials Section',
  showTestimonialsSection: 'Show Testimonials Section',
  footerContent: 'Footer Content',
  tagline: 'Tagline',
  contactEmail: 'Contact Email',
  contactPhone: 'Contact Phone',
  footerLogoOptional: 'Footer Logo (optional)',
  footerLogoHint: 'Leave blank to use the Branding logo.',
  navigationColumns: 'Navigation Columns',
  column1Title: 'Column 1 Title',
  column2Title: 'Column 2 Title',
  column3Title: 'Column 3 Title',
  tabBranding: 'Branding',
  tabHero: 'Hero',
  tabFeatured: 'Featured',
  tabCanopy: 'Skincare',
  tabTestimonials: 'Testimonials',
  tabFooter: 'Footer',

  // Admin Dashboard extra
  manageOrders: 'Manage Orders',
  viewCustomers: 'View Customers',
  editProducts: 'Edit Products',
  shipped: 'Shipped',
  delivered: 'Delivered',

  // Admin Categories
  addCategory: 'Add Category',
  editCategory: 'Edit Category',
  createCategory: 'Create Category',
  updateCategory: 'Update Category',
  noCategoriesYet: 'No categories yet',
  addFirstCategory: 'Add your first category to organise products',
  colSlug: 'Slug',
  colStatus: 'Status',
  colEnglishName: 'English Name',
  colArabicName: 'Arabic Name',
  hidden: 'Hidden',
  slugLabel: 'Slug *',
  slugPlaceholder: 'e.g. helmets',
  slugHint: "Slug cannot be changed (it's used as a product category key).",
  visibleInStore: 'Visible in store',
  deleteCategory: 'Delete Category?',
  deleteCategoryWarning: 'This will also delete all translations for this category. Products using this slug will lose their category label.',
  categoriesCount: 'categories',
  categoryCount: 'category',
  nameLabel: 'Name',
  nameRequired: 'Name *',

  // Admin Permissions
  roleDefaults: 'Role Defaults',
  employeeOverrides: 'Employee Overrides',
  loadingPermissions: 'Loading permissions...',
  roleDefaultsInfo: 'Role defaults apply to all employees with that role unless they have custom overrides. Super Admin and Admin always have full access.',
  employeeOverridesInfo: 'Override permissions for individual employees. When custom permissions are set they replace the role defaults entirely. Click "Reset to Role" to remove overrides.',
  saveRolePermissions: 'Save Role Permissions',
  savePermissions: 'Save Permissions',
  resetToRole: 'Reset to Role',
  customBadge: 'Custom',
  noEmployeesFound: 'No employees found',
  roleDefaultNotice: 'Using role defaults',

  // Admin Employees extra
  changePwd: 'Change Password',
  cancelPwdChange: 'Cancel Password Change',
  newPassword: 'New Password *',
  confirmNewPassword: 'Confirm New Password *',
  reenterNewPassword: 'Re-enter new password',
  noLinkedAccount: 'This employee has no linked login account. Password change will have no effect.',
  loginPassword: 'Login Password *',
  datePlaceholder: 'YYYY-MM-DD',
  emailCannotChange: 'Email cannot be changed after account creation.',
  authBadge: 'Auth',
  deleteEmployee: 'Delete Employee?',
  colHireDate: 'Hire Date',

  // Admin Products extra
  mainImage: 'Main Image',
  imageGallery: 'Image Gallery',
  deleteProduct: 'Delete Product?',
  badgePlaceholder: 'e.g. NEW, SALE',
  backToProducts: '← Back',
  saveChanges2: 'Save Changes',
  pricePlaceholder: '0.00',
  stockPlaceholder: '0',

  // Admin Coupons extra
  activeCoupon: 'Active Coupon',
  couponHint: 'Customers will enter this code at checkout',
  discountValueLabel: 'Discount Value *',
  minOrderLabel: 'Minimum Order Value ($)',
  minOrderPlaceholder: '0 (no minimum)',
  expiryPlaceholder: 'YYYY-MM-DD (leave blank = no expiry)',
  maxUsesLabel: 'Max Uses',
  maxUsesPlaceholder: 'Leave blank for unlimited',
  createCoupon: 'Create Coupon',

  // Admin Orders extra
  qtyLabel: 'Qty:',
  backToOrders: '← Back',

  // Admin Customers extra
  backToCustomers: '← Back',
  noCustomersFound: 'No customers found',

  // Admin Reviews extra
  deleteReview: 'Delete Review?',
  colDate2: 'Date',

  // General admin
  live: 'Live',
  preview: 'Preview',
  homepage: 'homepage',

  // Admin Login
  adminDashboard: 'Admin Dashboard',
  adminSignInSubtitle: 'Sign in to manage your store',
  adminEmailPlaceholder: 'Admin email',
  enterEmailAndPassword: 'Please enter your email and password.',
  invalidAdminCredentials: 'Invalid email or password.',
  signIn: 'Sign In',
  backToStore: 'Back to Store',

  // Admin Settings
  storeIdentityGroup: 'Store Identity',
  contactInformationGroup: 'Contact Information',
  socialLinksGroup: 'Social Links',
  commerceSettingsGroup: 'Commerce Settings',
  localizationGroup: 'Localization',
  adminInfoGroup: 'Admin Info',
  configureStoreDesc: "Configure your store's identity, contact info, social links, and commerce settings.",
  adminInfoDesc: 'Admin access credentials are set in code for security. To change the admin login, update the credentials in context/AdminContext.tsx.',
  defaultLoginCredentials: 'Default Login Credentials:',

  // MobileUnsupported
  visualEditorWebOnly: 'Visual Editor available on Web',
  visualEditorBody: 'Advanced direct editing with mouse is available only in the web admin dashboard.',
  visualEditorHint: 'Open the admin panel in a desktop browser to access the full visual editor.',
  featureClickSelect: 'Click-to-select elements',
  featureDragResize: 'Drag & resize blocks',
  featureInspector: 'Inspector panel',
  featureLivePreview: 'Live preview editing',

  // AdminMobileDashboard quick nav
  quickNavigation: 'Quick Navigation',

  // Permissions sections
  permGeneral: 'General',
  permCatalog: 'Catalog',
  permSales: 'Sales',
  permContent: 'Content',
  permAdmin: 'Admin',

  // Coupons remaining
  colCode: 'Code',
  colDiscount: 'Discount',
  colMinOrder: 'Min Order',
  colExpiry: 'Expiry',
  colUses: 'Uses',
  deleteCoupon: 'Delete Coupon?',
  deleteCouponWarning: 'This action cannot be undone.',
  updateCoupon: 'Update',
  couponCodeLabel: 'Coupon Code *',
  discountTypeLabel: 'Discount Type *',

  // Reviews remaining
  reviewerCol: 'Customer',
  submitted: 'Submitted',
  reviewDetailsTitle: 'Review Details',

  // Orders remaining
  orderItemsTitle: 'Order Items',
  updateStatusTitle: 'Update Status',

  // Customers remaining
  ordersStatLabel: 'Orders',
  totalSpentLabel: 'Total Spent',
  orderHistoryLabel: 'Order History',

  // Categories remaining
  slugRequired: 'Slug is required.',
  slugInvalid: 'Slug must be lowercase letters, numbers and hyphens only.',
  englishNameRequired: 'English name is required.',
  categoryUpdated: 'Category updated',
  categoryCreated: 'Category created',
  categoryDeleted: 'Category deleted',

  // Products remaining
  nameRequired2: 'Name *',
  descriptionField: 'Description',
  categoryField: 'Category',
  featuredField: 'Featured',
  nameArabic: 'Name (Arabic)',
  descArabic: 'Description (Arabic)',
  nameSpanish: 'Name (Spanish)',
  descSpanish: 'Description (Spanish)',
  nameGerman: 'Name (German)',
  descGerman: 'Description (German)',
  nameRussian: 'Name (Russian)',
  descRussian: 'Description (Russian)',
  priceField: 'Price ($)',
  stockField: 'Stock',
  productNameField: 'Name',

  // BlockSettingsPanel
  blockSettings: 'Block Settings',
  colors: 'Colors',
  bannerText: 'Banner Text',
  buttonUrl: 'Button URL',
  backgroundColor: 'Background Color',
  textColor: 'Text Color',
  maxProducts: 'Max Products',
  maxItems: 'Max Items',
  bannerPreviewText: 'Banner preview text here',

  // Wishlist
  myWishlist: 'My Wishlist',
  addedToWishlist: 'Added to favorites',
  removedFromWishlist: 'Removed from favorites',
  wishlistEmpty: 'Your wishlist is empty',
  wishlistEmptyDesc: 'Tap the heart icon on any product to save it here.',
  signInToSave: 'Sign in to save favorites',
  signInToSaveDesc: 'Create an account to save products and access your wishlist from any device.',
  clearWishlist: 'Clear Wishlist',
  clearWishlistConfirm: 'Remove all items from your wishlist?',
  clearAll: 'Clear All',
  browseProducts: 'Browse Products',

  // Nav labels (tab bar + drawer)
  navHome: 'Home',
  navShop: 'Shop',
  navSaved: 'Saved',
  navProducts: 'Products',
  navAllProducts: 'All Products',
  navCart: 'Cart',
  navAdminPanel: 'Admin Panel',
  navCanopyFinder: 'Match Filter',
  navAccount: 'Account',
  navAbout: 'About',

  // Canopy section on homepage
  canopyWeightQuestion: 'Skincare Collection',
  canopyJumpsQuestion: 'Coming Soon',

  // About / Contact page
  aboutUs: 'About Us',
  aboutTagline: 'Premium makeup trusted by beauty lovers worldwide',
  followUs: 'Follow Us',
  followSub: 'Stay connected with the community',
  contactWhatsapp: 'Contact us on WhatsApp',
  contactEmail: 'Send us an Email',
  contactPhone: 'Call Us',
  shippingPolicy: 'Shipping Policy',
  returnPolicy: 'Return Policy',
  deliveryTime: 'Delivery',
  shippingAreas: 'Coverage',
  shippingCost: 'Cost',
  returnDays: 'Returns',
  returnConditions: 'Conditions',
  returnRefund: 'Refunds',
  missionLabel: 'Our Mission',
  loadingContent: 'Loading content...',

  // Admin About editor
  adminAbout: 'About & Contact',
  aboutBrandTab: 'Brand',
  aboutSocialTab: 'Social',
  aboutContactTab: 'Contact',
  aboutShippingTab: 'Shipping',
  aboutReturnTab: 'Returns',
  brandName: 'Brand Name',
  brandTagline: 'Tagline',
  brandDescription: 'Brand Description',
  brandMission: 'Mission',
  instagramUrl: 'Instagram URL',
  instagramHandle: 'Instagram Handle',
  tiktokUrl: 'TikTok URL',
  tiktokHandle: 'TikTok Handle',
  facebookUrl: 'Facebook URL',
  facebookHandle: 'Facebook Page Name',
  whatsappNumber: 'WhatsApp Number (digits only)',
  contactEmailLabel: 'Support Email',
  contactPhoneLabel: 'Phone',
  shippingTitle: 'Section Title',
  shippingDelivery: 'Delivery Time',
  shippingAreasLabel: 'Shipping Areas',
  shippingCostLabel: 'Shipping Cost',
  returnTitle: 'Section Title',
  returnDaysLabel: 'Return Window',
  returnConditionsLabel: 'Conditions',
  returnRefundLabel: 'Refund Process',
  copyrightText: 'Copyright Text',
  contentSavedOk: 'Saved!',
  saveAbout: 'Save Changes',

  // Product detail page
  specifications: 'Specifications',
  youMayAlsoLike: 'You May Also Like',
  skuLabel: 'SKU',

  // Canopy page - explanation text fragments
  canopyExplanationIntro: 'This recommendation is based on dermatological best practices. Your skin type and routine',
  canopyExplanationRange: 'determines an ideal product coverage of',
  canopyExplanationFormula: 'Product match = skin type + routine steps:',
  canopyExplanationMin: 'min',
  canopyExplanationMax: 'max',
  canopyWeightPlaceholderLbs: 'e.g. 185',
  canopyWeightPlaceholderKg: 'e.g. 84',

  // Admin reviews
  searchReviews: 'Search reviews...',
  reviewPending: 'Pending',
  reviewApproved: 'Approved',
  reviewRejected: 'Rejected',
  reviewUpdatedStatus: 'Status updated',
  reviewUpdateFailed: 'Failed to update review',
  reviewApprovedMsg: 'Review approved',
  reviewRejectedMsg: 'Review rejected',
  reviewDeletedMsg: 'Review deleted',
  reviewCountSingular: 'review',
  reviewCountPlural: 'reviews',

  // Admin orders
  productLabel: 'Product',
  statusUpdatedMsg: 'Status updated',

  // Admin customers
  ordersAndSpent: 'orders · $',

  // Search
  searchGear: 'Search beauty...',

  // Admin Shipping
  shipping: 'Shipping',
  shippingAdmin: 'Shipping',
  addShippingRule: 'Add Rule',
  editShippingRule: 'Edit Shipping Rule',
  shippingRules: 'Shipping Rules',
  noShippingRules: 'No shipping rules yet',
  noShippingRulesDesc: 'Add your first shipping rule to start charging delivery fees',
  shippingRuleAdded: 'Shipping rule added',
  shippingRuleUpdated: 'Shipping rule updated',
  shippingRuleDeleted: 'Rule deleted',
  deleteShippingRule: 'Delete Shipping Rule?',
  shippingFee: 'Shipping Fee',
  freeShippingMinimum: 'Free Shipping Minimum',
  governorate: 'Governorate',
  area: 'Area / District',
  shippingUnavailable: 'Shipping unavailable for this area',
  freeShipping2: 'Free shipping for this order',

  // Auto-translate
  autoTranslate: 'Auto-Translate',
  translationDone: 'Translations applied',
  translationFailed: 'Auto-translate failed',
  productNameRequired: 'Enter a product name first',
  overwriteTranslations: 'Overwrite existing translations',
  overwriteOnDesc: 'All 4 languages will be regenerated',
  overwriteOffDesc: 'Only missing or English-fallback translations will be filled',
  reTranslate: 'Re-Translate',
  reTranslateDesc: 'Translate the English name and description into AR, ES, DE, and RU using AI.',
  translationsUpdated: 'Translations updated successfully',
  translating: 'Translating...',
};
